services:

  postgres:
    image: 'postgres:16.4'
    command: postgres -c 'max_connections=200' # 기본 설정은 100 이나, 200까지 확장
    environment:
      - 'POSTGRES_DB=insight'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=insight'
    ports:
      - '54324:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "63794:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
