services:

  mysql:
    image: 'mysql:8.0.41'
    environment:
      - 'MYSQL_DATABASE=insight'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=insight'
    ports:
      - '33064:3306'
    volumes:
      - mysql_insight_data:/var/lib/mysql
    networks:
      - insight_network

  redis:
    image: redis:alpine
    ports:
      - "63794:6379"
    volumes:
      - redis_insight_data:/data
    networks:
      - insight_network

volumes:
  mysql_insight_data:
  redis_insight_data:

networks:
  insight_network:
